version: '3.7'
services: 
    db:
      container_name: docker-local-postgres
      image: postgres
      volumes:
        - "./data:/var/lib/postgresql/data"
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: password