version: '3.7'
services:
  mongodb_database:
    # Image name.
    image: mongo
    environment:
      # Set username and password  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # Set port.
    ports:
      - 27017:27017
    # Set volume  
    volumes:
      - ./data:/data/db
    restart: always 